# Generated by Django 4.1.5 on 2023-04-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_ark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pod_category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='sport_ark.pod_category', verbose_name='Категория продукта'),
            preserve_default=False,
        ),
    ]
