# Generated by Django 4.1.5 on 2023-04-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_ark', '0002_product_pod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod_category',
            name='category_roditel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_ark.category', verbose_name='Категорий родитель'),
        ),
    ]
