# Generated by Django 4.1.5 on 2023-04-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_ark', '0003_alter_pod_category_category_roditel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod_category',
            name='category_img',
            field=models.ImageField(default=2, upload_to='pod_category/img/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pod_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sport_ark.pod_category', verbose_name='Под Категория продукта'),
        ),
    ]
