# Generated by Django 4.1.5 on 2023-04-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_ark', '0005_zakaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='geo_position',
            field=models.CharField(default=2, max_length=300, verbose_name='Адрес пользователья'),
            preserve_default=False,
        ),
    ]
