# Generated by Django 4.1.5 on 2023-04-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_ark', '0006_cuser_geo_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
