# Generated by Django 4.1.5 on 2023-04-17 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_ark', '0007_remove_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingproduct',
            name='rating',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка товару'),
        ),
    ]
